### ISSUE TITLE
Image URL Validation

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-awright022#4]
#### As a user I want to be prevented from submitting invalid image URLs.

__Story__:

We quickly got up to speed providing our users the ability to add images to our
service. How cool are all the images they are adding? But wait, what are all
these broken image placeholders? We would like to avoid that. In order to do so
we will need to add some validation to our model in order to increase the
chance that the data submitted actually corresponds to an image URL.

__Acceptance criteria__:
- [ ] I cannot successfully save an image with an invalid URL.
- [ ] An error message is associated with the appropriate input field on
  failure.

__Discussion Topic__:
- [ ] What is a valid image URL?

__Dependencies__:
- Save Image Link

**Comment by awright022** [comment]
I believe I included this in #18 - relevant commits: 
https://github.com/AppFolioOnboarding/image-sharer-awright022/pull/18/commits/82e7644b0986982dd5c3c6a366a42599458d3397

https://github.com/AppFolioOnboarding/image-sharer-awright022/pull/18/commits/229b2b85eb7bc006b7e3ba0d4f7fb8e7a36afcda
